{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namePrefix }}manager-rolebinding
  labels:
    {{- include "opensandbox-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namePrefix }}manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "opensandbox-controller.serviceAccountName" . }}
  namespace: {{ include "opensandbox-controller.namespace" . }}
{{- end }}
