{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}controller-manager-metrics-service
  namespace: {{ include "opensandbox-controller.namespace" . }}
  labels:
    {{- include "opensandbox-controller.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - name: https
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.service.port }}
  selector:
    {{- include "opensandbox-controller.selectorLabels" . | nindent 4 }}
{{- end }}
