{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opensandbox.serviceAccountName" . }}
  namespace: {{ include "opensandbox.namespace" . }}
  labels:
    {{- include "opensandbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
