apiVersion: sandbox.opensandbox.io/v1alpha1
kind: BatchSandbox
metadata:
  labels:
    app.kubernetes.io/name: opensandbox
    app.kubernetes.io/managed-by: kustomize
  name: batchsandbox-pool-sample
  namespace: opensandbox
spec:
  poolRef: pool-sample
  replicas: 2
  expireTime: "2026-12-03T12:55:41Z"
